# .github/workflows/pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'higienizados/*.md' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate simple redirect HTML
        run: |
          mkdir -p _site
          
          # Find the latest .md file in higienizados/
          LATEST_MD=$(find higienizados -name "*.md" -type f -printf '%T@ %p\n' 2>/dev/null | sort -n | tail -1 | cut -d' ' -f2-)
          
          if [ -z "$LATEST_MD" ]; then
            echo "<h1>Nenhum diário higienizado encontrado</h1>" > _site/index.html
            exit 0
          fi
          
          # Create simple redirect HTML
          cat > _site/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=./$LATEST_MD">
            <title>Redirecionando...</title>
          </head>
          <body>
            <p>Redirecionando para o último diário higienizado...</p>
            <p><a href="./$LATEST_MD">Clique aqui se não for redirecionado automaticamente</a></p>
          </body>
          </html>
          EOF
          
          # Copy the markdown files to _site
          cp -r higienizados _site/

      - name: Commit and push site
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _site/ 
          git diff --staged --quiet || git commit -m "Update GitHub Pages site: $(date '+%Y-%m-%d %H:%M')"
          git push