name: Process Diário Oficial

on:
  push:
    branches: [ main, master ]
    paths:
      - 'diarios/*.pdf'
      - 'PROMPT.md'
      - '.github/workflows/process-diario.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils jq
          npm init -y
          npm install axios
          pip install markitdown
      
      - name: Convert PDFs to markdown
        run: |
          for pdf in diarios/*.pdf; do
            if [ -f "$pdf" ]; then
              filename=$(basename "$pdf" .pdf)
              output_file="simplificados/${filename}.md"
              if [ ! -f "$output_file" ]; then
                python -m markitdown "$pdf" -o "$output_file"
                echo "Converted: $pdf -> $output_file"
              else
                echo "Skipped: $output_file already exists"
              fi
            fi
          done
      
      - name: Process document with OpenRouter
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: ./process-pdf.sh
      
      - name: Move processed.md to docs directory
        run: |
          mkdir -p docs
          mv processed.md docs/
      
      - name: Commit and push processed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/processed.md simplificados/
          git diff --staged --quiet || git commit -m "chore(automation): processa diário oficial de $(date '+%Y-%m-%d %H:%M')"
          git push