# .github/workflows/simplifique.yml
name: Simplifique Diário Oficial
on: [workflow_dispatch]

jobs:
  process-diario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Process PDF with OpenRouter API
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Extract text from PDF
          PDF_FILE=$(find . -name "*.pdf" -type f | head -1)
          if [ -z "$PDF_FILE" ]; then
            echo "No PDF file found"
            exit 1
          fi
          
          echo "Processing PDF: $PDF_FILE"
          pdftotext "$PDF_FILE" extracted_text.txt
          
          # Read prompt from PROMPT.md
          PROMPT=$(cat PROMPT.md)
          INPUT=$(cat extracted_text.txt)
          
          # Create request body
          BODY=$(jq -n --arg prompt "$PROMPT" --arg input "$INPUT" \
            '{
              "model": "openai/gpt-oss-20b:free",
              "messages": [
                {
                  "role": "user",
                  "content": ($prompt + "\n\nEntrada:\n" + $input)
                }
              ]
            }')

          # Call OpenRouter API
          mkdir -p simplificados
          BASENAME=$(basename "$PDF_FILE" .pdf)
          OUTPUT_FILE="simplificados/${BASENAME}_simplificado.md"
          
          curl -s -L \
            -H "Authorization: Bearer $OPENROUTER_API_KEY" \
            -H "Content-Type: application/json" \
            https://openrouter.ai/api/v1/chat/completions \
            -d "$BODY" \
          | jq -r '.choices[0].message.content' > "$OUTPUT_FILE"

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add simplificados/
          git diff --staged --quiet || git commit -m "Add simplified diário: $(basename *.pdf .pdf)"
          git push

      - uses: actions/upload-artifact@v4
        with:
          name: diario-simplificado
          path: simplificados/

